-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 22:17:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mdp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mdp` ;

-- -----------------------------------------------------
-- Schema mdp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mdp` DEFAULT CHARACTER SET utf8 ;
USE `mdp` ;

-- -----------------------------------------------------
-- Table `mdp`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shortName` VARCHAR(32) NOT NULL,
  `fullName` VARCHAR(128) NOT NULL,
  `nicknames` VARCHAR(128) NULL,
  `country` INT NOT NULL,
  `description` VARCHAR(2048) NULL,
  `birthday` DATE NULL,
  `gender` VARCHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `countryInPersons_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `countryInPersons`
    FOREIGN KEY (`country`)
    REFERENCES `mdp`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`imagetypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`imagetypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`personimages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`personimages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person` INT NOT NULL,
  `type` INT NOT NULL,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `personInPersonImages_idx` (`person` ASC) VISIBLE,
  INDEX `imageTypeInPersonImages_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `personInPersonImages`
    FOREIGN KEY (`person`)
    REFERENCES `mdp`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imageTypeInPersonImages`
    FOREIGN KEY (`type`)
    REFERENCES `mdp`.`imagetypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`personroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`personroles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `personInPersonRoles_idx` (`person` ASC) VISIBLE,
  INDEX `roleInPersonRoles_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `personInPersonRoles`
    FOREIGN KEY (`person`)
    REFERENCES `mdp`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roleInPersonRoles`
    FOREIGN KEY (`role`)
    REFERENCES `mdp`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(512) NOT NULL,
  `nickname` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `country` INT NOT NULL,
  `description` VARCHAR(256) NULL,
  `birthday` DATE NULL,
  `gender` VARCHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `countryInUsers_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `countryInUsers`
    FOREIGN KEY (`country`)
    REFERENCES `mdp`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`userimages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`userimages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `type` INT NOT NULL,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userInUserImages_idx` (`user` ASC) VISIBLE,
  INDEX `imageTypeInUserImages_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `userInUserImages`
    FOREIGN KEY (`user`)
    REFERENCES `mdp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imageTypeInUserImages`
    FOREIGN KEY (`type`)
    REFERENCES `mdp`.`imagetypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`demographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`demographics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`interests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `description` VARCHAR(256) NULL,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`interestdemographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`interestdemographics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `interest` INT NOT NULL,
  `demographic` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `interestInInterestDemographics_idx` (`interest` ASC) VISIBLE,
  INDEX `demographicInInterestDemographics_idx` (`demographic` ASC) VISIBLE,
  CONSTRAINT `interestInInterestDemographics`
    FOREIGN KEY (`interest`)
    REFERENCES `mdp`.`interests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `demographicInInterestDemographics`
    FOREIGN KEY (`demographic`)
    REFERENCES `mdp`.`demographics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shortName` VARCHAR(32) NOT NULL,
  `fullName` VARCHAR(128) NOT NULL,
  `country` INT NOT NULL,
  `foundingDate` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `countryInCompanies_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `countryInCompanies`
    FOREIGN KEY (`country`)
    REFERENCES `mdp`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`companyimages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`companyimages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company` INT NOT NULL,
  `type` INT NOT NULL,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `companyInComanyImages_idx` (`company` ASC) VISIBLE,
  INDEX `imageTypeInCompanyImages_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `companyInComanyImages`
    FOREIGN KEY (`company`)
    REFERENCES `mdp`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imageTypeInCompanyImages`
    FOREIGN KEY (`type`)
    REFERENCES `mdp`.`imagetypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`ageratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`ageratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`works` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shortName` VARCHAR(32) NOT NULL,
  `fullName` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `media` INT NOT NULL,
  `ageRating` INT NULL,
  `mainParticipantRole` INT NOT NULL,
  `mainParticipant` VARCHAR(64) NULL,
  `releaseDate` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `mediaInWorks_idx` (`media` ASC) VISIBLE,
  INDEX `ageRatingInWorks_idx` (`ageRating` ASC) VISIBLE,
  INDEX `rolesInWorks_idx` (`mainParticipantRole` ASC) VISIBLE,
  CONSTRAINT `mediaInWorks`
    FOREIGN KEY (`media`)
    REFERENCES `mdp`.`medias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ageRatingInWorks`
    FOREIGN KEY (`ageRating`)
    REFERENCES `mdp`.`ageratings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rolesInWorks`
    FOREIGN KEY (`mainParticipantRole`)
    REFERENCES `mdp`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`workothernames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`workothernames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workInWorkOtherNames_idx` (`work` ASC) VISIBLE,
  CONSTRAINT `workInWorkOtherNames`
    FOREIGN KEY (`work`)
    REFERENCES `mdp`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`workimages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`workimages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work` INT NOT NULL,
  `type` INT NOT NULL,
  `url` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workInWorkImages_idx` (`work` ASC) VISIBLE,
  INDEX `imageTypeInWorkImages_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `workInWorkImages`
    FOREIGN KEY (`work`)
    REFERENCES `mdp`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imageTypeInWorkImages`
    FOREIGN KEY (`type`)
    REFERENCES `mdp`.`imagetypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`workcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`workcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work` INT NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workInWorkCategories_idx` (`work` ASC) VISIBLE,
  INDEX `categoryInWorkCategories_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `workInWorkCategories`
    FOREIGN KEY (`work`)
    REFERENCES `mdp`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoryInWorkCategories`
    FOREIGN KEY (`category`)
    REFERENCES `mdp`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`workdemographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`workdemographics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work` INT NOT NULL,
  `demographics` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `workInWorkDemographics_idx` (`work` ASC) VISIBLE,
  INDEX `demographicsInWorkDemographics_idx` (`demographics` ASC) VISIBLE,
  CONSTRAINT `workInWorkDemographics`
    FOREIGN KEY (`work`)
    REFERENCES `mdp`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `demographicsInWorkDemographics`
    FOREIGN KEY (`demographics`)
    REFERENCES `mdp`.`demographics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`companyroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`companyroles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `companyInCompanyRoles_idx` (`company` ASC) VISIBLE,
  INDEX `roleInCompanyRoles_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `companyInCompanyRoles`
    FOREIGN KEY (`company`)
    REFERENCES `mdp`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roleInCompanyRoles`
    FOREIGN KEY (`role`)
    REFERENCES `mdp`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(512) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userInReviews_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `userInReviews`
    FOREIGN KEY (`user`)
    REFERENCES `mdp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`companyreviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`companyreviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review` INT NOT NULL,
  `company` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `companyInCompanyReviews_idx` (`company` ASC) VISIBLE,
  INDEX `reviewInCompanyReviews_idx` (`review` ASC) VISIBLE,
  CONSTRAINT `companyInCompanyReviews`
    FOREIGN KEY (`company`)
    REFERENCES `mdp`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviewInCompanyReviews`
    FOREIGN KEY (`review`)
    REFERENCES `mdp`.`reviews` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`workreviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`workreviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review` INT NOT NULL,
  `work` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `reviewInCompanyReviews_idx` (`review` ASC) VISIBLE,
  INDEX `workInWorkReviews_idx` (`work` ASC) VISIBLE,
  CONSTRAINT `workInWorkReviews`
    FOREIGN KEY (`work`)
    REFERENCES `mdp`.`works` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviewInWorkReviews`
    FOREIGN KEY (`review`)
    REFERENCES `mdp`.`reviews` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdp`.`personreviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mdp`.`personreviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review` INT NOT NULL,
  `person` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `reviewInCompanyReviews_idx` (`review` ASC) VISIBLE,
  INDEX `personInPersonReviews_idx` (`person` ASC) VISIBLE,
  CONSTRAINT `personInPersonReviews`
    FOREIGN KEY (`person`)
    REFERENCES `mdp`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviewInPersonReviews`
    FOREIGN KEY (`review`)
    REFERENCES `mdp`.`reviews` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
